language: scala
scala:
    - 2.11.4
jdk:
    - openjdk7
cache:
    directories:
    - $HOME/.ivy2/cache
before_install:
- git config --global user.email "liska.jakub@gmail.com"
- git config --global user.name "Jakub Liska"
- git config --global push.default simple
- mkdir $HOME/temp
script:
- sbt ++$TRAVIS_SCALA_VERSION clean fullOptJS
after_success:
- cp target/scala-2.11/replayed-opt.js README.md README.json $HOME/temp
- git checkout gh-pages
- cp $HOME/temp/* ./
- git add replayed-opt.js README.md README.json
- git commit -m "auto deploy from CI"
- git push

# tests are not executed because they depend on PhantomJS 2.0 that hasn't been released yet
# therefore they need to be run manually, leaving the rest of the work on travis